apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout/rollout.yaml
- services/service.yaml
- ingress/ingress.yaml
- secrets/secret.yaml
- configmaps/configmap.yaml
- namespaces/canary-app.yaml
- preview-service/preview-service.yaml

images:
  - name: alexmt/rollouts-demo
    newTag: red
  # - name: argoproj/rollouts-demo
